<h1>An error occured</h1>

<h2>
    <?php echo $this->message ?>
</h2>

<?php if($this->showBacktrace): ?>

<h3>Exception information:</h3>
<p>
    <b>Message: </b>
    <?php echo $this->exception->getMessage() ?>
</p>

<h3>Stack trace:</h3>
<pre>
<?php echo $this->exception->getTraceAsString() ?>
</pre>

<h3>Request parameters</h3>
<pre>
<?php var_dump($this->request->getParams()) ?>
</pre>

<?php endif ?>
