<?php
define('APPLICATION_PATH', realpath(dirname(__FILE__) . '/../') . '/');

define('APPLICATION_PROCEDURE_DEVELOPMENT', 'DEVELOPMENT');
define('APPLICATION_PROCEDURE_PRODUCTION', 'PRODUCTION');
define('APPLICATION_PROCEDURE_TESTING', 'TESTING');
